site_name: P5.js lernen
theme: readthedocs

pages:
- Home: "index.md"
- Erste Schritte: "firststeps.md"
- P5.js in eine HTML-Seite einbinden: "p5standalone.md"
- Running Orc: "runningorc.md"
- Spieleprogrammierung 1: "spieleprogrammierung01.md"
- Spieleprogrammierung 2: "spieleprogrammierung02.md"
- Spaß mit Emojis: "p5emoji.md"
- Anhänge:
    - P5.js und RubyFrontier: "p5rubyfrontier.md"
    - RubyFrontier als P5.js-IDE: "p5rubyfrontieride.md"
    - Zwei Canvases mit P5.js: "p52canvases.md"

markdown_extensions:
- footnotes
- admonition

- smarty:
    smart_quotes: False

repo_url: https://github.com/kantel/p5js
edit_uri: blob/master/docs

site_dir: "/Applications/MAMP/htdocs/p5js"

extra_css: [css/user.css]

extra_javascript:
    - js/p5.min.js
    - js/p5.dom.min.js
    - js/p5.sound.min.js

google_analytics: ["UA-89422194-1", "auto"]
